### ISSUE TITLE
Text alignment "center" causes error

### ISSUE THREAD

**Issue by K4zuki** [at-wat/eagle2svg#13]
### Conditions
MacOS Sierra
Eagle 7.5.0
Python 3.6

### Reproducing files
See attached
[relay_isolator_1A.zip](https://github.com/at-wat/eagle2svg/files/1598867/relay_isolator_1A.zip)

### Error messages
```
$ eagle2svg relay_isolator_1A.sch
Traceback (most recent call last):
  File "/usr/local/bin/eagle2svg", line 11, in <module>
    sys.exit(render_main())
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/render.py", line 17, in render_main
    data = eagle_parser.Eagle(argv[1])
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_parser.py", line 128, in __init__
    self.data = Schematic(data['eagle']['drawing']['schematic'])
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_parser.py", line 74, in __init__
    super(Schematic, self).__init__(data)
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_parser.py", line 13, in __init__
    library = eagle_element.Library(library_data)
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_element.py", line 1013, in __init__
    package = Package(package_data)
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_element.py", line 933, in __init__
    super(Package, self).__init__(data)
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_element.py", line 820, in __init__
    self.texts.append(Text(text_data))
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_element.py", line 554, in __init__
    if align[1] == 'left':
IndexError: list index out of range
```
```
Traceback (most recent call last):
  File "/usr/local/bin/eagle2svg", line 11, in <module>
    sys.exit(render_main())
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/render.py", line 17, in render_main
    data = eagle_parser.Eagle(argv[1])
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_parser.py", line 130, in __init__
    self.data = Board(data['eagle']['drawing']['board'])
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_parser.py", line 19, in __init__
    super(Board, self).__init__(data)
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_parser.py", line 13, in __init__
    library = eagle_element.Library(library_data)
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_element.py", line 1013, in __init__
    package = Package(package_data)
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_element.py", line 933, in __init__
    super(Package, self).__init__(data)
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_element.py", line 820, in __init__
    self.texts.append(Text(text_data))
  File "/usr/local/lib/python3.6/site-packages/eagle2svg/eagle_element.py", line 554, in __init__
    if align[1] == 'left':
IndexError: list index out of range
```

### Suspected cause of error
in `eagle_element.py` text parser expects "[top/bottom/center]-[left/right/center]" style for alignment, but "center-center" is not used, "center" is used instead.

**Comment by at-wat** [comment]
https://github.com/at-wat/eagle2svg/blob/61d1b2fd17875c73faeeb7ab7ddb8eee2dcc77e5/eagle2svg/eagle_element.py#L570-L575

**Comment by at-wat** [comment]
@K4zuki `center` align has been fixed. Please try it out.

**Comment by K4zuki** [comment]
confirmed fixes, Thanks!
